#ifndef DEFINITIONS_H
#define DEFINITIONS_H 
/*  
 *  WARNING! This file has been automatically generated by configure.
 *  Any changes to it will be overwritten the next time configure is run.
 */
/*==============================================================================
 * FILE: defs.h.in
 *
 * PURPOSE: Template file for defs.h.  When 'configure' is run, a new defs.h
 *   file will be created (overwriting the last) from this template in which
 *   various cpp macros are defined selected from the options available here.  
 *
 * TO BY-PASS CONFIGURE: copy this file into defs.h, and edit the cpp macros
 *   by hand.
 *============================================================================*/

/*----------------------------------------------------------------------------*/
/*  macros which define physics and algorithm
 *  (user modified via configure) */

/* Version identifier when configure was last run */
#define CONFIGURE_DATE "Fri Jun 29 08:35:32 EDT 2018"

/* Problem generator with which Athena is compiled */
#define A_PROBLEM "cpaw1d"

/* ADIABATIC or ISOTHERMAL or ... */
#define ISOTHERMAL
#define EOS_STR "ISOTHERMAL"

#if defined(ISOTHERMAL) /* || defined PIECEWISE_POLYTROPE ... */
#define BAROTROPIC        /* P = P(rho) */
#elif !defined(ADIABATIC)  /* P = P(eth) = (gamma - 1)*eth */
#define GENERAL_EOS       /* P = P(rho,eth) */
#endif

/* Real: DOUBLE_PREC or SINGLE_PREC */
#define DOUBLE_PREC

/* debug mode: DEBUG or OPTIMIZE */
#define OPTIMIZE

/* Write ghost cells in outputs: WRITE_GHOST_CELLS or NO_WRITE_GHOST_CELLS */
#define NO_WRITE_GHOST_CELLS

/* MPI parallelism: MPI_PARALLEL or NO_MPI_PARALLEL */
#define NO_MPI_PARALLEL

/* Shearing box: SHEARING_BOX or NO_SHEARING_BOX */
#define NO_SHEARING_BOX

/* delta-f: DELTA_F or FULL_F */
#define FULL_F

/* variable-dt: VARIABLE_DT or FIXED_DT */
#define FIXED_DT

/*----------------------------------------------------------------------------*/
/* macros associated with numerical algorithm (rarely modified) */

/* nghost = Number of Ghost Cells 
 * num_digit = Number of digits in data dump file
 * MAXLEN = maximum line length in input parameter file
 */

/* Number of ghost cells must be MAX(3,nfpass) */
enum {nghost = 5,
      num_digit = 4};
#define MAXLEN 256

/*----------------------------------------------------------------------------*/
/* general purpose macros (never modified) */
#ifndef MIN
#define MIN(a,b) ( ((a) < (b)) ? (a) : (b) )
#endif
#ifndef MAX
#define MAX(a,b) ( ((a) > (b)) ? (a) : (b) )
#endif
#define SIGN(a) ( ((a) < 0.) ? -1. : 1. )
#define SQR(x) ( (x)*(x) )
#define STR(x) #x
#define SQRT2 1.4142135623730951
#define ONE_OVER_SQRT2 0.7071067811865475
#define PI       3.14159265358979323846
#define ONE_3RD  0.3333333333333333
#define TWO_3RDS 0.6666666666666667
#define FOUR_3RDS 1.333333333333333
#define TINY_NUMBER 1.0e-20
#define HUGE_NUMBER 1.0e+20

/*----------------------------------------------------------------------------*/
/* computed macros based on above choices (never modified) */

 enum {NVAR = 3};
#ifdef DRIVING
 enum {NFORCE = 3};
#else
 enum {NFORCE = 0};
#endif

/*----------------------------------------------------------------------------*/

#ifdef MPI_PARALLEL
/* Integer constants to identify MPI messages sent in various parts of code */
enum {LtoR_tag,
      RtoL_tag,
      boundary_particle_tag,
      ch_rundir0_tag,
      ch_rundir1_tag
};
#endif /* MPI_PARALLEL */

#ifdef SHEARING_BOX
enum SS2DCoord {xy, xz};
#endif

#endif /* DEFINITIONS_H */
